# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 654a2f43771ffda8a0ca739cef9703a533267e5056a92568c8c1e2dcb4c73c7958f7f1273911d423e89913928ee95286e224981ce2d2eb353d8aa7475f738271

test:
  secret_key_base: ec12bbd29616946068b406bfd38e05f652a0ec1706870018e1ea2c94041728f7765bc1af1a941418da513daec65e40c28ea1a7dc54df54bbb4206e70e9121dce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
